CREATE TABLE app_users(
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    user_password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE groups (
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR2(100) NOT NULL,
    created_by NUMBER NOT NULL, -- user_id of admin
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group_admin FOREIGN KEY (created_by) REFERENCES app_users(user_id)
);

CREATE TABLE group_members (
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_admin CHAR(1) DEFAULT 'N', -- 'Y' if admin, else 'N'
    CONSTRAINT fk_member_group FOREIGN KEY (group_id) REFERENCES groups(group_id),
    CONSTRAINT fk_member_user FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

CREATE TABLE expenses (
    expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER NOT NULL, -- group_id 
    paid_by NUMBER NOT NULL, -- user_id who paid
    description VARCHAR2(255), -- description of group
    amount NUMBER(12,2) NOT NULL,
    expense_date DATE DEFAULT SYSDATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_expense_group FOREIGN KEY (group_id) REFERENCES groups(group_id),
    CONSTRAINT fk_expense_user FOREIGN KEY (paid_by) REFERENCES app_users(user_id)
);

CREATE TABLE expense_shares (
    share_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id NUMBER NOT NULL, -- 
    user_id NUMBER NOT NULL,
    share_amount NUMBER(12,2) NOT NULL,
    is_paid CHAR(1) DEFAULT 'N',
    CONSTRAINT fk_share_expense FOREIGN KEY (expense_id) REFERENCES expenses(expense_id),
    CONSTRAINT fk_share_user FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

alter TABLE app_users ADD public_id VARCHAR2(36) UNIQUE NOT NULL;

select * from app_users;
select * from groups;
select * from group_members;
select full_name, user_id, is_admin, group_id from app_users natural JOIN GROUP_MEMBERS; 
select * from expenses;
select * from expense_shares;
TRUNCATE table app_users;
DESCRIBE app_users;

alter table app_users modify created_at default systimestamp;

delete from app_users where user_id = 30;

alter table group_members add CONSTRAINT uq_group_user UNIQUE (group_id, user_id);

ALTER TABLE expense_shares
ADD CONSTRAINT uq_expense_user UNIQUE (expense_id, user_id);

ALTER TABLE group_members
ADD CONSTRAINT chk_is_admin
CHECK (is_admin IN ('Y','N'));

ALTER TABLE expense_shares
ADD CONSTRAINT chk_is_paid
CHECK (is_paid IN ('Y','N'));

CREATE INDEX idx_group_members_group ON group_members(group_id);
CREATE INDEX idx_group_members_user ON group_members(user_id);

CREATE INDEX idx_expenses_group ON expenses(group_id);
CREATE INDEX idx_expenses_paid_by ON expenses(paid_by);

CREATE INDEX idx_expense_shares_expense ON expense_shares(expense_id);
CREATE INDEX idx_expense_shares_user ON expense_shares(user_id);
drop INDEX idx_expense_shares_expense;
-- INNER JOIN 
Select u.full_name, gm.group_id from app_users u
join GROUP_MEMBERS gm on u.user_id = gm.user_id;

-- LEFT JOIN
select u.USER_ID, u.full_name, u.email from APP_USERS u
left join GROUP_MEMBERS gm on u.user_id = gm.USER_ID;

select g.group_id, g.group_name, au.full_name as created_by from groups g
inner join app_users au on g.created_by = au.user_id;

SELECT g.GROUP_ID, g.GROUP_NAME, au.FULL_NAME as created_by
FROM groups g
INNER JOIN app_users au
ON g.created_by = au.user_id
WHERE au.user_id = 61;

select distinct g.group_id, g.group_name, au.full_name as created_by
from group_members gm 
join groups g on gm.group_id = g.group_id
join app_users au on g.created_by = au.user_id
where gm.user_id = 61
order by g.group_id desc;
