CREATE TABLE app_users(
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    user_password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE groups (
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR2(100) NOT NULL,
    created_by NUMBER NOT NULL, -- user_id of admin
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group_admin FOREIGN KEY (created_by) REFERENCES app_users(user_id)
);

CREATE TABLE group_members (
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_admin CHAR(1) DEFAULT 'N', -- 'Y' if admin, else 'N'
    CONSTRAINT fk_member_group FOREIGN KEY (group_id) REFERENCES groups(group_id),
    CONSTRAINT fk_member_user FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

CREATE TABLE expenses (
    expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER NOT NULL,
    paid_by NUMBER NOT NULL, -- user_id who paid
    description VARCHAR2(255),
    amount NUMBER(12,2) NOT NULL,
    expense_date DATE DEFAULT SYSDATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_expense_group FOREIGN KEY (group_id) REFERENCES groups(group_id),
    CONSTRAINT fk_expense_user FOREIGN KEY (paid_by) REFERENCES app_users(user_id)
);

CREATE TABLE expense_shares (
    share_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    share_amount NUMBER(12,2) NOT NULL,
    is_paid CHAR(1) DEFAULT 'N',
    CONSTRAINT fk_share_expense FOREIGN KEY (expense_id) REFERENCES expenses(expense_id),
    CONSTRAINT fk_share_user FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

